---
# Preámbulo con paquetes y definiciones básicas
# Se incluyen los comandos mínimos de LaTeX
#title: Mi título
author:
 - Fulanito\and
 - Perenganito
header-includes:
# Estos son paquetes de LaTeX que uso habitualmente
  - \usepackage{array}
  - \usepackage{booktabs}
  - \usepackage{amsmath}
  - \usepackage{amssymb}
  - \usepackage{mathtools}
  - \usepackage{braket}
  - \usepackage[shortlabels]{enumitem}
  - \usepackage[spanish]{babel}
  - \decimalpoint
  - \usepackage{graphicx}
  - \usepackage{caption}
  - \renewcommand{\and}{\\}
  - \renewcommand{\arraystretch}{1.2}
  - \usepackage{booktabs}
  - \usepackage{float}
  - \usepackage[font=small,labelfont=bf]{caption}
  - \usepackage{fancyhdr}
  - \newcommand{\mb}[1]{\mathbb{#1}}
output: pdf_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include = FALSE, echo = FALSE}
##  LIBRERÍAS
# Aquí vamos a incluir las librerías que necesitemos
# En donde se pongan pedazos de código, únicamente se comentará
# Es BUENA PRÁCTICA poner las librerías al principio, por ello las ponemos aquí
# library(library_name)
```

# Aquí va todo el contenido

_Quizá con letras cursivas_ o `código`, o *remarcadas*.

---
<!-- por si necesitamos incluir referencias -->
\begin{thebibliography}{99}
  \bibitem{autor23}
      Nombre del autor,
      \emph{Título del libro},
      núm. ed.,
      Editorial,
      año.
      
\end{thebibliography}
